### ISSUE TITLE
Configure Gemspec and CI

### ISSUE THREAD

**Issue by stevepolitodesign** [stevepolitodesign/rails_mvp_authentication#1]
Something like the following should work.

```yml
name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'         
      - name: Install dependencies
        run: bundle install
      - name: Create database
        run: bundle exec rails db:setup
      - name: Run Standard
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rails test
```
